### ISSUE TITLE
Warning: Ambiguous class resolution, "Drupal\Component\Utility\Random" 

### ISSUE THREAD

**Issue by heddn** [jhedstrom/DrupalDriver#104]
When running composer install/update/require -o, I get the following warning:

Warning: Ambiguous class resolution, "Drupal\Component\Utility\Random" was found in both "$baseDir . '/web/core/lib/Drupal/Component/Utility/Random.php" and "vendor/drupal/drupal-driver/src/Drupal/Component/Utility/Random.php", the first will be used.

**Comment by dww** [comment]
I'm also seeing the same thing when trying to use composer on Pantheon via CircleCI + Terminus as documented here: https://pantheon.io/docs/guides/github-pull-requests.
