### ISSUE TITLE
[D8] Support LinkHandler options

### ISSUE THREAD

**Issue by aoturoa** [jhedstrom/DrupalDriver#106]
Currently the LinkHandler disregards and input for the options since it sets a empty array().
Maybe the $value[2] could be used, split similarly to the Title and Uri?

We use TableNodes to populate the Link value using: "Link title - http://urihere.com"
We'd like to supply the link options in the form of an array like:
"Link title - http://urihere.com - attributes[target]=_blank"

Pull request for this issue: https://github.com/jhedstrom/DrupalDriver/pull/107

**Comment by jonathanjfshaw** [comment]
This issue has been resolved and can be closed,  #107 was merged.
