### ISSUE TITLE
Remove any specific Drupal 7 logic from AbstractCore when dealing with field translations

### ISSUE THREAD

**Issue by ademarco** [jhedstrom/DrupalDriver#12]
Follow up issue after merging of #11

The current solution breaks in Drupal 8 since ```\Drupal\Driver\Cores\AbstractCore``` is supposed to be Drupal core agnostic, so in there we cannot refer to Drupal 7 specifics like the ```LANGUAGE_NONE``` constant, which is not available in Drupal 8.

One possible solution would be to add the $entity object to the field handler constructor, so we can delegate all core specific logic to handler implementations, so from:

```php
public function getFieldHandler($entity_type, $field_name, $language);
```
 We would have:

```php
public function getFieldHandler($entity, $entity_type, $field_name);
```

**Comment by ademarco** [comment]
\cc @dutchiexl

**Comment by dutchiexl** [comment]
Ok, I will look into this

**Comment by ademarco** [comment]
Great, thanks! We should also, at some point, write some test coverage for this. For that we have a feature that is enabled when TravisCI is fired-up, it is under ```fixtures/drupal7/modules/behat_test```: do you have any specific configuration that would help us in writing effective tests? (e.g.specific coontrib modules like "Entity Translations", etc.).

**Comment by dutchiexl** [comment]
Not exactly, field is translatable is form the field module, which is in core.

**Comment by dutchiexl** [comment]
As suggested, I put the entity in the abstract handler, which is version specific, and out of AbstractCore

**Comment by dutchiexl** [comment]
Can this be closed ?

**Comment by ademarco** [comment]
I guess we should wait for #13 to be merged into master.

**Comment by jhedstrom** [comment]
#13 has been merged.

**Comment by ademarco** [comment]
:+1:
