### ISSUE TITLE
Incorrect negation of bundles in Drupal/Driver/Fields/Drupal8/EntityReferenceHandler.php

### ISSUE THREAD

**Issue by pwolanin** [jhedstrom/DrupalDriver#147]
Looks like there is an incorrect negation operator - this change would fix it?

```
--- a/src/Drupal/Driver/Fields/Drupal8/EntityReferenceHandler.php
+++ b/src/Drupal/Driver/Fields/Drupal8/EntityReferenceHandler.php
@@ -26,7 +26,7 @@ class EntityReferenceHandler extends AbstractHandler {
 
     // Determine target bundle restrictions.
     $target_bundle_key = NULL;
-    if (!$target_bundles = $this->getTargetBundles()) {
+    if ($target_bundles = $this->getTargetBundles()) {
       $target_bundle_key = $entity_definition->getKey('bundle');
     }
 
```

**Comment by jhedstrom** [comment]
Hmm, I'm not sure. What issue is this causing? I haven't worked on this part of the code in a very long time.

**Comment by pwolanin** [comment]
@jhedstrom  it looks as though the bundle filtering will never be applied because of this negation.  So if 2+ nodes have the same title but different bundles the query may find the wrong one.

I can try to make an example that fails.

**Comment by Berdir** [comment]
Agreed, this is wrong. Right now, it gets the target bundle key if there are *no* target bundles. Obviously we need a target bundle key if there *are* target bundles.

This made a test fail for me because it is selecting a term with the same name from another vocabulary.

Will create a MR.
