### ISSUE TITLE
Make setCoreFromVersion() work with Drupal7, not only Drupal8.

### ISSUE THREAD

**Issue by PieterDC** [jhedstrom/DrupalDriver#15]
`$driver->setCoreFromVersion();` does not work with core Drupal7 because its `__construct()` requires a `$random` argument, in contrary to core Drupal8.

We work around this by setting the Driver core property explicitly instead of using setCoreFromVersion(): `$driver->core = new \Drupal\Driver\Cores\Drupal7($path, $uri, new Random())`

But ideally, both core drivers should work alike.

**Comment by jhedstrom** [comment]
Attempting a fix in #17.

Thanks for reporting this!
