### ISSUE TITLE
isLegacyDrush() iillegal offset 'drush-version'

### ISSUE THREAD

**Issue by Skullywag** [jhedstrom/DrupalDriver#150]
I have a bamboo based build system that is reporting failed Behat tests due to:

Warning: Illegal string offset 'drush-version' in vendor/drupal/drupal-driver/src/Drupal/Driver/DrushDriver.php line 139

Ive since updated my local version to the latest as well but dont see the issue when running the tests locally.

Running on Acquia btw if that has any impact. Running Drupal 7 on Drush 8.

Anyone got any ideas why this would be the case?

EDIT - it seems Acquia have removed part of this in some of their Drupal 8 build tool stuff:

https://github.com/acquia/blt/commit/1f5419b84bcaa90fe83f7004b4cf5664405a5df5

Is the code used in isLegacyDrush correct based on the above?

**Comment by jhedstrom** [comment]
That actually looks like a legitimate failure for drush 8. I'll try and push a fix today.

**Comment by jhedstrom** [comment]
Could you check if #151 fixes your issue? I'm also curious what version of drush is on the server?

**Comment by Skullywag** [comment]
The version would have been whatever composer grabs for drush/drush:~8
