### ISSUE TITLE
Don't check access when referencing entities

### ISSUE THREAD

**Issue by jonathanjfshaw** [jhedstrom/DrupalDriver#158]
We should add ->accessCheck(FALSE) to our EntityQuery in the D8 EntityReferenceHandler.

Otherwise it will fail when asked to create entities that reference other entities the current user cannot access. The Driver shouldn't really care about the current user unless explicitly told to, as it's methods are often used to set up context for a test rather than describe actions of a test user.

**Comment by jhedstrom** [comment]
This is the equivalent issue: https://www.drupal.org/project/drupal/issues/2931028
