### ISSUE TITLE
Stay in Drupal root instead of going back to the previous folder

### ISSUE THREAD

**Issue by PieterDC** [jhedstrom/DrupalDriver#16]
In our implementation of DrupalDriver - we don't use Behat but we do use PHPUnit and Selenium - we go to the Drupal root folder after bootstrapping to keep  `libraries_get_libraries()` from failing.

        // Bootstrap Drupal.
        $driver->bootstrap();

        // Needed for code that does not use DRUPAL_ROOT, but instead relies
        // on Drupal root being the current working directory.
        // Like libraries_get_libraries().
        chdir($drupal_directory);

Why is DrupalDriver going back to the previous folder instead of staying at the Drupal root folder?

**Comment by jhedstrom** [comment]
I've never tested it without changing back. I'll have to test with behat/drupal extension to see if it works to just stay in the drupal root.

**Comment by marcingy** [comment]
I have been having some issues with tests falling in d8 due to missing plugins at 'random' points in tests and removing the called to 

chdir($current_path);

seems to resolve the issue.

**Comment by jhedstrom** [comment]
I'd accept a PR that removes this. I think staying at the drupal root after bootstrapping will be more stable (Drush [does this](https://github.com/drush-ops/drush/blob/master/lib/Drush/Boot/bootstrap.inc#L363)).

**Comment by marcingy** [comment]
Pull request created here https://github.com/jhedstrom/DrupalDriver/pull/25

**Comment by pfrenssen** [comment]
The pull request from #25 was accepted, this issue can be closed.
