### ISSUE TITLE
DrupalDriver core needs a configGetOriginal() method

### ISSUE THREAD

**Issue by upchuk** [jhedstrom/DrupalDriver#194]
We currently have a `configGet()` method but we also need a `configGetOriginal()` so that we can use in the extension in the `ConfigContext`. This is so that it backs up the correct config value and not the potentially overridden one.

PR will follow.

**Comment by jhedstrom** [comment]
Closing this out. I just restarted the build on the DrupalExtension PR, so we can follow-up there if it needs more work.
