### ISSUE TITLE
Suggestion for content creation with domains

### ISSUE THREAD

**Issue by dutchiexl** [jhedstrom/DrupalDriver#20]
I am using the the next given:
<pre>
 Given I a viewing a "News" content:
      | title      | News feature: News item 1 |
      | body       | This is a news item       |
      | field_date | 2018-02-25 07:45:45       |
      | language   | en                        |
</pre>

Anyone has a suggestion on how to add domain selection from domain access module? The domain information is not included in field.info.class.inc

Should this be for example in de Drupal7 Class (nodeCreate), or should we create some kind of hook to alter this ...

**Comment by jhedstrom** [comment]
Doesn't just setting `$node->domain` (or whatever domain module uses) work here?

**Comment by dutchiexl** [comment]
I did this:

<pre>
 /**
   * Creates content of the given type, provided in the form:
   * | title     | My node        |
   * | Field One | My field value |
   * | author    | Joe Editor     |
   * | status    | 1              |
   * | domain    | 1              |
   * | ...       | ...            |
   *
   * @Given I created a/an :type( content):
   */
  public function createNode($type, TableNode $fields) {
    $node = (object) array(
      'type' => $type,
    );
    foreach ($fields->getRowsHash() as $field => $value) {
      if ($field == "domains") {
        $node->domain_site = TRUE;
        $node->domain_source = $value;
        $value = array($value => $value);

      }
      $node->{$field} = $value;
    }

    $this->nodeCreate($node);
  }
</pre>
