### ISSUE TITLE
Drupal 10 compatibility broke taxonomy term creation in patch version

### ISSUE THREAD

**Issue by Kingdutch** [jhedstrom/DrupalDriver#259]
https://github.com/jhedstrom/DrupalDriver/pull/250/commits/8177f645a229f40ba88b4c20daffe1a124c54445 changed how taxonomy term creation worked in 2.2.1 but this broke the functionality.

`parent` may be empty if multiple taxonomies are created in a single `Given` block as pointed out in https://github.com/jhedstrom/DrupalDriver/pull/257

Additionally `id` is not the right base field for the query but it should be `name`.

Finally the entityQuery does not return loaded entities but returns IDs so calling `->id()` on it will break as well.

**Comment by Kingdutch** [comment]
Hosting static patch so it can be easily used to fix our CI [DrupalDriver-pr-260.patch](https://github.com/jhedstrom/DrupalDriver/files/10139569/DrupalDriver-pr-260.patch.txt)

**Comment by bkosborne** [comment]
Came across this as well. Thanks for posting a patch!

**Comment by bkosborne** [comment]
Actually I just tested this and it works with composer as-is.

`composer require citation-style-language/styles:0.0.149` downloads the latest version.

`composer require citation-style-language/styles:0.0.148` goes to the previous commit/tag.

I think this can be closed as fixed.
