### ISSUE TITLE
Decide on a set of coding standards

### ISSUE THREAD

**Issue by pfrenssen** [jhedstrom/DrupalDriver#39]
The number of contributors to the project is growing. It would be good for the consistency of the code base to follow a particular coding standard. Currently a mix of standards is used.

Since this project is closely related to Drupal we can maybe opt to use the Drupal coding standards?

**Comment by jhedstrom** [comment]
I've tried to keep the coding standards compliant with Drupal's coding standards, so let's continue on that path.
