### ISSUE TITLE
conf_path() does not exist for drupal 8

### ISSUE THREAD

**Issue by dutchiexl** [jhedstrom/DrupalDriver#59]
Running the behat test, gives me ```Call to undefined function Drupal\Driver\Cores\conf_path() in /Library/WebServer/Documents/cegeka/behat-demo/vendor/drupal/drupal-driver/src/Drupal/Driver/Cores/Drupal8.php on line 291````
Whe I look in the source of drupal 8, conf_path is no longer a function.

**Comment by LionsAd** [comment]
This is fixed.
