### ISSUE TITLE
Creating content with language doesn't work

### ISSUE THREAD

**Issue by dutchiexl** [jhedstrom/DrupalDriver#9]

**Comment by dutchiexl** [comment]
I added some code to make field translation work. Can you check it out and poissbly pull? I would be happy to refactor some of it if you have an idea about putting the code somewhere else.

**Comment by jhedstrom** [comment]
I merged the PR. Thanks again!

**Comment by dutchiexl** [comment]
I refactored the code, so that it is more version specific which would solve the drupal8 issue
